# Generated by Django 5.0.2 on 2024-03-01 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('todo', '0002_alter_task_options_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_todo', to='profiles.profile'),
        ),
    ]
