# Generated by Django 5.0.1 on 2024-01-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('title_game', models.CharField(blank=True, max_length=500)),
                ('description_game', models.TextField(blank=True)),
                ('picture1', models.ImageField(blank=True, upload_to='', verbose_name='picture1')),
                ('picture2', models.ImageField(blank=True, upload_to='', verbose_name='picture2')),
                ('pdf', models.FileField(blank=True, upload_to='pdf')),
            ],
        ),
        migrations.CreateModel(
            name='LudicJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateTimeField(blank=True, null=True)),
                ('assessement', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecorderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, upload_to='')),
                ('sentence', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
