# Generated by Django 4.0.1 on 2022-01-25 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ludicjourney',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_ludicjourney', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='pathology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.pathology'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='therapist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_exercice', to='profiles.profile'),
        ),
    ]
