# Generated by Django 4.0 on 2021-12-17 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ludic_journey',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.user'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='pathology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.pathology'),
        ),
    ]
