# Generated by Django 5.0.1 on 2024-01-16 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_exercice', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='ludicjourney',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='ludicjourney',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_ludicjourney', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='pathology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.pathology'),
        ),
        migrations.AddField(
            model_name='recordermessage',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_recorder', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='recordermessage',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_recorder', to='profiles.profile'),
        ),
    ]
