# Generated by Django 4.0 on 2022-01-12 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_user_state'),
        ('exercises', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ludicjourney',
            name='profile',
        ),
        migrations.AddField(
            model_name='exercise',
            name='therapist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_exercice', to='profiles.user'),
        ),
        migrations.AddField(
            model_name='ludicjourney',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_ludicjourney', to='profiles.user'),
        ),
    ]
