# Generated by Django 4.0.2 on 2022-02-18 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_bio'),
        ('exercises', '0004_remove_ludicjourney_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathology',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_pathology', to='profiles.profile'),
        ),
    ]
