# Generated by Django 4.0.2 on 2022-02-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_bio'),
        ('exercises', '0005_pathology_therapist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathology',
            name='therapist',
        ),
        migrations.AddField(
            model_name='pathology',
            name='therapist',
            field=models.ManyToManyField(blank=True, null=True, related_name='therapist_pathology', to='profiles.Profile'),
        ),
    ]
