# Generated by Django 4.0.2 on 2022-02-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_remove_pathology_therapist_pathology_therapist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathology',
            name='therapist',
        ),
    ]
