# Generated by Django 4.0.2 on 2022-02-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_remove_pathology_therapist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='picture1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='picture1'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='picture2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='picture2'),
        ),
    ]
