# Generated by Django 4.0.2 on 2022-02-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_therapist_pathology'),
        ('exercises', '0008_alter_exercise_picture1_alter_exercise_picture2'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description_game',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='title_game',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_exercice', to='profiles.profile'),
        ),
    ]
