# Generated by Django 4.0.2 on 2022-03-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_exercise_description_game_exercise_title_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ludicjourney',
            name='assessement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ludicjourney',
            name='journey_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
