# Generated by Django 4.0.3 on 2022-03-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_auto_20220324_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathology',
            name='therapist_pathology',
        ),
    ]
