# Generated by Django 4.1.7 on 2023-03-10 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_profile_therapist_pathology'),
        ('exercises', '0013_remove_pathology_therapist_pathology'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecorderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, upload_to='')),
                ('sentence', models.TextField(blank=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_recorder', to='exercises.exercise')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_recorder', to='profiles.profile')),
            ],
        ),
    ]
