# Generated by Django 4.1.7 on 2023-06-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_exercise_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordermessage',
            name='sentence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
