# Generated by Django 5.0.1 on 2024-01-16 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('shedule_online', models.URLField()),
                ('report', models.CharField(blank=True, max_length=500)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_workshop', to='profiles.profile')),
                ('therapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_workshop', to='profiles.profile')),
            ],
        ),
    ]
