# Generated by Django 4.0 on 2022-01-12 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_user_state'),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='speech_therapist',
        ),
        migrations.AddField(
            model_name='workshop',
            name='therapist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_workshop', to='profiles.user'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_workshop', to='profiles.user'),
        ),
    ]
