# Generated by Django 4.0.2 on 2022-02-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_remove_workshop_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='report',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
