# Generated by Django 4.0.1 on 2022-01-24 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Patient'), (2, 'Speech_Therapist')], default=2)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('review', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='pictures/')),
                ('pathology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_pathology', to='exercises.pathology')),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(null=True)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('zip_code', models.CharField(blank=True, max_length=5)),
                ('city', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
