# Generated by Django 4.0 on 2022-01-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Patient'), (2, 'Speech_Therapist')], default=2),
        ),
    ]
