# Generated by Django 4.0.2 on 2022-02-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_alter_exercise_picture1_alter_exercise_picture2'),
        ('profiles', '0007_profile_therapist_pathology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='therapist_pathology',
            field=models.ManyToManyField(blank=True, to='exercises.Pathology'),
        ),
    ]
